services:
  api:
    build:
      context: .
    container_name: bit-hrms-api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONSUL_URL=http://host.docker.internal:8500
    volumes:
      - /home/pix/bit/assets/hrms/development:/var/lib/media-files
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:latest
    container_name: nginx-bit-hrms
    ports:
      - "9000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
