services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.tests
    environment:
      - ConnectionStrings__Default=host=db;port=5432;database=testdb;username=postgres;password=postgres;
      - ConnectionStrings__Jobs=host=db;port=5432;database=testdb;username=postgres;password=postgres;
      - Serilog__WriteTo__0__Args__connectionString=host=db;port=5432;database=testdb;username=postgres;password=postgres;
      - Serilog__WriteTo__0__Name=PostgreSQL
      - Serilog__WriteTo__0__Args__tableName=logs
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    volumes:
      - test_data:/var/lib/postgresql/data

volumes:
  test_data:
