global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text.Json.Serialization;
global using System.Threading.Tasks;
global using Application.Common.Abstract;
global using Application.Common.Extensions;
global using Domain.Common;
global using Domain.Common.ValueObjects;
global using FluentValidation;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using static Domain.Common.Enums;
