name: Test Suite

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker Compose Up
        run: docker compose  --verbose -f docker-compose.tests.yml up -d --build
